#!/usr/bin/env python2

import re
import sys
from subprocess import check_output

data = sys.stdin.read()
last_date = check_output('git log --pretty=format:"%ad" --date=local -1', shell=True)
last_revision = check_output('git log --pretty=format:"%h" -1', shell=True)
data = re.sub('\$Date\$', '$Date: ' + last_date + '$', data)
print re.sub('\$Revision\$', '-' + last_revision, data),
